### PR TITLE
Git week1

### PR DESCRIPTION
**Pull request by Rajesh-Bhatt**
1 branch with 3 new files created!!!

### CODE REVIEW

**Comment by hirenkumar91** [comment]
Great work Rajesh,

for Future Assignments i will suggest use git commits at every stage of development,

for E.g 

whenever you create/delete New file.
change/update text 

you can merge your work

keep up good work.

**Comment by jason-vasilev** [comment]
Rejesh, remember to merge only after a mentor has reviewed and approve your PR

**Comment by Rajesh-Bhatt** [comment]
Ok, sure!!

**Comment by Rajesh-Bhatt** [comment]
> Great work Rajesh,
> 
> for Future Assignments i will suggest use git commits at every stage of development,
> 
> for E.g
> 
> whenever you create/delete New file. change/update text
> 
> you can merge your work
> 
> keep up good work.

Thank you!!!

**Pull request merged**
